### ISSUE TITLE
Lat Long control needs some refinement when re-rendering from already transcribed values

### ISSUE THREAD

**Issue by davidbairdala** [AtlasOfLivingAustralia/volunteer-portal#1]
A couple of points:

The format for the pair of lat/long widgets (one for lat, the other for long), are kept in sync (i.e. when the format for one changes, so does the other). This poses a slight problem when re-rendering as the format of the last control (of the pair) determines the format for both, and if a value is missing for the last control, it defaults to DMS, which obscures a decimal degree value in the top control

Some DMS formats are not being correctly identified by the lat long conversion routines

e.g. 27.6"

**Comment by sbearcsiro** [comment]
Bumping this from 2.0.1 to 2.1 as there won't be time to test it before the 2.0.1 release
