### ISSUE TITLE
Copy from previous task

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#103]
If you use the feature to copy from a previous task and the selected task has been validated the "Transcribe All Text" field doesn't get displayed or copied. This has happened in the AM Frit Flies 5 expedition which is basically being validated as its being transcribed.

**Comment by RhiannonStephens** [comment]
I have also had a request from Tiara to add the copy from previous function to their template UHIMInsectLabel

**Comment by sbearcsiro** [comment]
@RhiannonStephens this occurs because the "Transcribe All Text" has been changed by the validator.  The same behaviour would happen for any field that had been changed by the validator.  Do you want to copy the latest value for the field (ie the validator's value) or the user's previous value?  I think the latest value for the field is the way to go.

**Comment by RhiannonStephens** [comment]
@sbearcsiro there is a bug in the copy from previous button in that it doesn't copy over state and country.

**Comment by sbearcsiro** [comment]
@RhiannonStephens OK - for the states and counties there is code in the copy from previous to deliberately exclude the following fields:

locality, stateProvince, decimalLatitude, decimalLongitude, country, coordinateUncertaintyInMeters

I'm not 100% sure why they are excluded (possibly the first use of this feature was on a project in which records differed mostly by location?) but I can remove the exclusions if you like?

**Comment by RhiannonStephens** [comment]
@sbearcsiro ah I think we wanted to make it that people couldn't copy the decimal Lat and Long for some reason?? That's why the state and country wouldn't carry over because those fields came from the mapping tool. I can't remember why we excluded them. @snomelf do you remember why?

**Comment by sbearcsiro** [comment]
@snomelf @RhiannonStephens can I close this task?

**Comment by RhiannonStephens** [comment]
@sbearcsiro I guess?
