### ISSUE TITLE
Task images with spaces can't be opened in the transcribe page

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#106]
If a task is created from an image with a space in the filename then when the task is being transcribed or validated the image can not be loaded from the file system.

What happens is that the file is stored on the filesystem with a %20 in the filename in place of the spaces, whereas the filename in the database contains just spaces.

NOTE this includes other characters that require URL encoding, such as ['&', '\'', ',']

**Comment by sbearcsiro** [comment]
To work around this bug, ssh to the server, cd to the project directory under /data/volunteer-portal and run:

    find . -name '*%20*' -type f -exec bash -c 'cp "$1" "${1//%20/ }"' -- {} \;

**Comment by RhiannonStephens** [comment]
@patkyn did you fix this?

**Comment by patkyn** [comment]
Yes I believe this is fixed as part of https://github.com/AtlasOfLivingAustralia/volunteer-portal/commit/a7ce8343223088fc8a47bc14aac758d0496bf90c. 

Probably need to retest

**Comment by RhiannonStephens** [comment]
fixed
