### ISSUE TITLE
Export data from field note template

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#107]
The spreadsheet extracted as a “Single de-normalised CSV file” certainly contains all the data, but not in a very useful format – columns and columns of the dates the sightings occurred on, followed by columns and columns of people mentioned on those dates, followed by columns and columns of the species sighted (see attached). Basically the data is scattered across hundreds of empty cells. I can manipulate the spreadsheet to make it useable, but it will take some time. 

Ideally I’d like to extract the data in the exact format it went IN – see below. I’ve added the column “externalIdentifier” to identify which page/diary the data came from, but apart from that the table I’ve mocked up below is identical to the table the volunteers enter the data into. It would then be a very simple matter of separating the people mentions (Party Names) from the species sightings and we would have two invaluable datasets (in a very user friendly format).

Is there any way this could be made possible? 

Thank you, as always, for your time, Nicole

![image](https://cloud.githubusercontent.com/assets/10238220/8073592/9b6b4756-0f6a-11e5-80a9-cd0ba55e450a.png)

**Comment by sbearcsiro** [comment]
Change existing ZIP file export to populate dataset.csv with individual record data.

**Comment by RhiannonStephens** [comment]
@patkyn @sbearcsiro in regards to our conversation yesterday about formatting. I looked at http://www.transcribe-bentham.da.ulcc.ac.uk/td/Help:Transcription_Guidelines to see how they do their formatting. They seem to be the only transcription site to actually do formatting. Anyway it looks like it might be a bit complicated for the volunteers, what do you think?
