### ISSUE TITLE
Feedback for transcribers

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#108]
@sbearcsiro trying to think of a more automated way of giving transcribers feedback. Be good if the validator could make a note and then the transcriber could somehow access that note through a my notebook tab?? Anyway something to think about, obviously you have heaps of stuff on but just wanted you to keep it in the back of your mind. Survey says more people want feedback. I can give them feedback for AM stuff but not for other institutions, thought there might be a better way.

**Comment by sbearcsiro** [comment]
Current thinking is:

Tab on user's notebook
Show tasks the user transcribed which were subsequently changed by validator or have a validation note
Modal dialog or separate page that shows changes made by validtor to transcriber's fields and shows validator comment.
Track which of these have been seen by user to show them a unread notification on the My Profile drop down.

**Comment by RhiannonStephens** [comment]
Hey @patkyn, i had a look at the feedback.
A couple of things:
![image](https://cloud.githubusercontent.com/assets/10238220/14709762/acf6836a-0815-11e6-8f0d-642630afc687.png)
can there be a notification on my profile on the front page
after you look at the notification it disappears. can it stay so it can be referred back later, any new ones sort to the top

**Comment by RhiannonStephens** [comment]
Hi @patkyn, @sbearcsiro and @snomelf 

I think we may need to rethink the notifications feature. It hasn’t quite worked like I had hoped. 

Some feedback I have received has included:

•	It is taking a long time for lists in the notebook to load
•	don’t like the notifications appearing all the time.
•	Some volunteers do not want to know about every full stop or space that has been removed from the transcription by validators
•	Tasks have not been locked (see below).
•	An admin person asked if this feature could be turned off for them

I think it may be better if the transcriber can only see the validator notes field. That way if the validator sees something that the transcriber keeps doing they can comment in the notes field.

What do you think?

**Comment by RhiannonStephens** [comment]
Have two options buttons for volunteers in notifications:
1 - Show just the validator notes field ie they wont get notified everytime something is changed just when the validator writes a note
2 - Show all the detail ie get notified every time something in their tasks have been changed
The button will need to 'save' for that volunteer so they dont have to keep changing it all the time
