### ISSUE TITLE
Stats and Reporting

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#109]
A stats page for DigiVol in the Admin stats button. 
Things to add:
New volunteers per day/week
Active volunteers per day/week
Volunteer hours per day (for work for dole, etc)
Top transcribers weekly/monthly (if you miss the leaderboard for the last day of the month there is currently no way of getting that info) (Historical honour board data)
Transcriptions per day (also per institution)
Validations per day (also per institution)
Average tasks per hour

**Comment by RhiannonStephens** [comment]
Also add the expedition collection manager to expedition summary report

**Comment by RhiannonStephens** [comment]
http://www.libcrowds.com/statistics/

**Comment by sbearcsiro** [comment]
Replace "Volunteer hours per day (for work for dole, etc)" with "Report for time period showing number of transcriptions per volunteer per project".

**Comment by sbearcsiro** [comment]
Roll "Average tasks per hour" into 
Transcriptions per day (also per institution)
Validations per day (also per institution)

as a per day / 24 hours

**Comment by sbearcsiro** [comment]
Allow various reports to be run for arbitrary date ranges

**Comment by RhiannonStephens** [comment]
Just looking back at previous stuff and also things that we have had to provide for WeDigBio etc i think it would be good if we could have:

- average transcription time (broken down to specimens vs field notes)
- hourly contribution totals (this one to show if something like an event has altered the activity)
- city and country of users (currently only cities within Australia show??)

**Comment by sbearcsiro** [comment]
Move "city and country of users" into a separate task.

**Comment by sbearcsiro** [comment]
Using our current data model it's impossible to create a useful "average transcription time" so we're going to break that out into a separate task.

**Comment by patkyn** [comment]
To add Export to Excel for the stats
