### ISSUE TITLE
CSS issues with new template

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/volunteer-portal#123]
* bootstrap `label`s are broken due to absolute position and `display:none`
* `badge`s have no background so appear like regular text. This will break existing content.
* `pagination` items use blue colouring - change to link colour (see `.pagination > li > a, .pagination > li > span`)

**Comment by nickdos** [comment]
Grid view issues:

![image](https://cloud.githubusercontent.com/assets/532845/10358524/f09a608a-6dda-11e5-8af9-8da3af12e007.png)

institution name extending beyong box:

![image](https://cloud.githubusercontent.com/assets/532845/10358533/0e449e7a-6ddb-11e5-8436-bf8b94d5e25c.png)

**Comment by nickdos** [comment]
Also project (expedition) titles are actually links but they neither indicate this via font colour or underline nor do they change when mouse-over. Only indication is cursor changes to hand. This is not good for accessibility.

**Comment by nickdos** [comment]
Institution list page CSS:

```
.thumbnail.institution a {
    display: block;
    min-height: 250px;
    line-height: 50px;
    padding-top: 90px; }
```

results in **any** links in the div.institution.thumbnail block being rendered as a block elelment the same size as the image. So this rule needs to be moved to a class. E.g. `<a class='institutionLogo'>`

**Comment by RhiannonStephens** [comment]
@sbearcsiro hasn't this been fixed?

**Comment by sbearcsiro** [comment]
@RhiannonStephens yep, this isn't necessary any more
