### ISSUE TITLE
Update data resource creation in the ALA

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/volunteer-portal#124]
Digivol resources created in the ALA need:
license and attribution for the data
image metadata - license, attribtuion, rights, creator
assigned to the DigiVol data provider
Do they need institution and collection codes where they are in Australian institutions?

**Comment by sbearcsiro** [comment]
`/ws/harvesting` endpoint is currently broken in production.  These endpoints, `/ws/harvesting` and `/ws/biocacheData`, should be fixed before proceeding.
