### ISSUE TITLE
Convert DigiVol Forum to new design

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#134]
Still TODO
- [x] Forum search results
- [x] Create Post button
- [x] Sorting columns do not work
- [x] Click on a topic ~~seems to~~ does crash
- [x] Expedition thumbnail image in topic column
- [x] Inactive BG colour in Expedition Forums tab, help icon near search box
- [x] Project Forum page
- [x] Topic/post pages

**Comment by aruizca** [comment]
@sbearcsiro Would you mind elaborating the point "Inactive BG colour in Expedition Forums tab, help icon near search box" please? Don't know what either of the two tasks mean?

**Comment by sbearcsiro** [comment]
@aruizca in this screenshot:

![image](https://cloud.githubusercontent.com/assets/1750790/10987516/1ee59428-8488-11e5-889c-d4903803f74a.png)

there is a rogue help icon near the search box and the inactive projects have the old background colour.  Hope that helps :grey_question:
