### ISSUE TITLE
Change image resizing

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#143]
- [x] Replace existing image resizing for one that only scales width to 600px maintaining aspect ratio
- [x] Apply resizeAndCrop to display image in expeditions thumbnail grid and featured
- [x] Remove institution banner, institution image
- [x] Apply fix width to institution logo on list 
- [x] Add expedition feature image with size advice

**Comment by aruizca** [comment]
IMO the prompt image recommended size should state recommended size, but with this plugin we can pretty much make sure that the layout always looks nice:
https://github.com/Traackr/resizeAndCrop
If the resulting resize and crop make the image pixely, the more clear will be for the responsible that image has to be update. I just would not force it to have a concrete fixed width and height, but rather a recommended size and proportion (e.g. 4:3)
