### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#149]
- [x] Expedition front page: Citizen Scientists -> Volunteers
- [x] Notebook page: Record location: add space between name and You, remove captial Y from You. 
![image](https://cloud.githubusercontent.com/assets/1750790/10927848/5b101bd6-82f7-11e5-890f-992f5f062241.png)

**Comment by RhiannonStephens** [comment]
Expedition front page - Citizen Scientists needs to be changed to Volunteers
