### ISSUE TITLE
Static content pages

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#152]
We need content for or to remove these links

![image](https://cloud.githubusercontent.com/assets/1750790/10927696/0ea6d9d4-82f6-11e5-950c-4a0c52e93b12.png)

**Comment by RhiannonStephens** [comment]
[DigiVol static pages.docx](https://files.zenhub.io/564e94297ec9ca497289d03b)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
