### ISSUE TITLE
"Delete all tasks" fails if any task has a forum post attached.

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#159]
Attempting to delete all tasks when at least one of those tasks has a forum topic will fail with a cryptic (to the user) error message:

![image](https://cloud.githubusercontent.com/assets/1750790/11108859/e7a6168e-893e-11e5-905d-497cb4d0aac5.png)

**Comment by cdausmus** [comment]
This looks to have been fixed previously, no longer reproducable.
