### ISSUE TITLE
Badges/Achievement page

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#168]
[Achievement Badges.docx](https://files.zenhub.io/564e95297ec9ca497289d044)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

Although I do prefer this page as is

**Comment by sbearcsiro** [comment]
All these badges should be implemented in dev now.

@RhiannonStephens The images in the doc seem to be reversed in a lot of cases (ie the file name suggests the icon is for the expert badge but you've used it in the doc for the non-expert badge).  Can you double check the badges in dev are using the right image?

**Comment by RhiannonStephens** [comment]
@sbearcsiro yeah I changed them around a bit. All good. Could you just change Transcribed to Completed in a few of the badge descriptions?
