### ISSUE TITLE
AM Specimen Template

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#171]
Lat and Long from Label fields 
![image](https://cloud.githubusercontent.com/assets/10238220/11386161/141bcc2a-9373-11e5-8817-7d6bc843e0dd.png)
In Firefox 42.0 (tho I haven't tested this) cant see lat/long values as they are too small and the mapping tool dialog is also too small.

**Comment by RhiannonStephens** [comment]
Actually don't need these symbols anymore, only need them for Transcribe all text box
![image](https://cloud.githubusercontent.com/assets/10238220/11412471/95c61d70-9431-11e5-9e62-ee505b7ca12a.png)

**Comment by RhiannonStephens** [comment]
Reduce font size for Adjust uncertainty field
![image](https://cloud.githubusercontent.com/assets/10238220/11412509/ef70693e-9431-11e5-9e29-822320ab2e8c.png)

**Comment by RhiannonStephens** [comment]
Mapping tool: Location data does not line up horizontally with Longitude, Latitude and Location.
![image](https://cloud.githubusercontent.com/assets/10238220/11412532/1ab0339a-9432-11e5-84b3-211b749d3656.png)

**Comment by RhiannonStephens** [comment]
Mapping tool: Location data headings do not line up vertically
![image](https://cloud.githubusercontent.com/assets/10238220/11412535/27d857dc-9432-11e5-99e3-deedfeb1dc3c.png)

**Comment by RhiannonStephens** [comment]
I get a Red warning, but no fields indicated in red
![image](https://cloud.githubusercontent.com/assets/10238220/11412574/820a4454-9432-11e5-940e-d95e94c02bc7.png)
Red Warning needs three buttons (or two buttons and an X) Continue | Cancel | Re-submit
![image](https://cloud.githubusercontent.com/assets/10238220/11412600/e8c21352-9432-11e5-9433-a46d16be7d2f.png)
 
Red Warning: CONTINUE button has an incorrect action of CANCEL
![image](https://cloud.githubusercontent.com/assets/10238220/11412601/ec32b5f0-9432-11e5-9522-97f82f1cf4d9.png)
 
Red Warning message: Once this message appears, there doesn't seem to be a way to submit the record anyway.
Yellow warning. Problem fields are not indicated
 
![image](https://cloud.githubusercontent.com/assets/10238220/11412602/f25fdfe8-9432-11e5-9ac3-abf8aeac3089.png)

**Comment by RhiannonStephens** [comment]
Transcription saved page: Change action and order of options.
![image](https://cloud.githubusercontent.com/assets/10238220/11412605/0feabe8e-9433-11e5-8656-84e510e7691a.png)
On this page the most important option *** TRANSCRIBE ANOTHER TASK *** is given the smallest writing, and hidden in a list of less-important options.

Change the order:
Transcribe another task   <-------- FIRST
Return to the saved task
Go to project start page 
View my stats

Change the font size and highlight the Transcribe another task heading

Change the default action: so that *** TRANSCRIBE ANOTHER TASK *** works by hitting a carriage return

Change the words of "Return to project start page" to "Go to project start page" (A different verb for each line)

**Comment by RhiannonStephens** [comment]
@sbearcsiro quite a few of the templates have 
![image](https://cloud.githubusercontent.com/assets/10238220/11413129/97f86c94-9439-11e5-8f30-2c711c66ceca.png)
The font needs to be smaller to fit in the field and they dont need the symbols
includes Belgium templates and I just made on called PennStateUni Herbarium

**Comment by sbearcsiro** [comment]
@RhiannonStephens The text being too tall for the select boxes appears to only be a problem on windows, doesn't happen on my mac.  We should probably get Peter to chime in here on the best way to fix it.

**Comment by sbearcsiro** [comment]
@RhiannonStephens I've updated the text on the button for the red warning but the behaviour here seems to be working - clicking continue the button puts the submission buttons back.  AFAIK this is how it has always worked.  The field indication should be fixed, however.

**Comment by sbearcsiro** [comment]
@RhiannonStephens could you run through this to confirm these issues are taken care of

**Comment by RhiannonStephens** [comment]
@sbearcsiro all good. I will close it
