### ISSUE TITLE
Expedition Front Page

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#172]
Could the link to the tutorials open on a new page i.e. a new tab?

**Comment by sbearcsiro** [comment]
@RhiannonStephens for the tutorial links on the expedition front page (ie the ones that appear in the modal dialog), you need to go into the project settings, go to tutorial links, edit the link and change the target to "Open link in a new window":

![image](https://cloud.githubusercontent.com/assets/1750790/11388514/2f0111a4-938b-11e5-9241-dcfbe4bf21bd.png)

**Comment by RhiannonStephens** [comment]
@sbearcsiro oops! I knew that!

**Comment by RhiannonStephens** [comment]
@sbearcsiro now I remember, those drop down boxes haven't worked for me for ages that's why I don't use them any more.
![image](https://cloud.githubusercontent.com/assets/10238220/11388576/eb3f2b6c-938b-11e5-91c7-a1ee6062f0cd.png)

**Comment by sbearcsiro** [comment]
@RhiannonStephens why does your pop up window have more options than mine?

**Comment by RhiannonStephens** [comment]
@sbearcsiro ha ha it doesn't matter cause none of them work!!

**Comment by sbearcsiro** [comment]
This should be fixed now
