### ISSUE TITLE
WingTags Template

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#176]
P[Template planning.pptx](https://files.zenhub.io/56551f927ec9ca49728a043e)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
Planning for new WingTag template.
Template is similar to questionaireTemplate but needs to be able to answer questions about several animals in the one image.

**Comment by sbearcsiro** [comment]
No longer necessary
