### ISSUE TITLE
Who created the expedition

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#180]
It would be really good to see which admin user created an expedition so that if there is a problem with that expedition we would know who to contact

**Comment by RhiannonStephens** [comment]
@sbearcsiro I'm not really sure where to find this?

**Comment by sbearcsiro** [comment]
This only shows up for projects that know who created them.  Any projects that existed prior to this change won't have the attribute set, so it won't show up on them.

**Comment by RhiannonStephens** [comment]
And will it show in the Expedition summary report? or somewhere in the settings?

**Comment by RhiannonStephens** [comment]
Shows in expedition settings
