### ISSUE TITLE
Expedition Admin page

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#182]
Expedition admin page. Search box doesn't seem to do anything. Eg a search for a catalog number doesn't find it, hitting return after writing into the search box unexpectedly does nothing.
![image](https://cloud.githubusercontent.com/assets/10238220/11412760/aee4bc0a-9434-11e5-8d0b-85c4ad2165bc.png)

**Comment by sbearcsiro** [comment]
Closed by commit in #181
