### ISSUE TITLE
Add transcribed tasks section to project index page

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#185]
The Beaconmaker design includes a transcribed tasks section in the project index page of a completed project.

Still to determine:
- only include if the project is completed?
- what page does it link to?  Task Forum Topic page?  A new read only summary page?
- How does this interact with #137 (Archived projects)?

**Comment by RhiannonStephens** [comment]
@sbearcsiro don't understand what this is

**Comment by sbearcsiro** [comment]
Scroll down to transcribed records on this page: http://www.designbymakers.com/dev/digivol/100515/expedition-austmus-complete-old.html
