### ISSUE TITLE
Speed improvements for stats/leaderboard sidebar

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#190]
Investigate adding caching for stats/leaderboard results (maybe for 1 minute?), so that the leaderboard sections don't take so long to load.

Also investigate splitting stats/leaderboard functions so that they can be loaded separately?

**Comment by cdausmus** [comment]
After discussion at team meeting, decided that recent performance improvements (CPU and memory) were enough. Closing this for now.
/cc @AdamWoodsAM
