### ISSUE TITLE
Update CSIRO logo in footer

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#198]
Use up to date CSIRO logo in front page footer.  See http://my.csiro.au/Business-Units/Operations/Communication/CSIRO-Branding/CSIRO-logos.aspx

**Comment by RhiannonStephens** [comment]
@sbearcsiro I'm in the process of emailing the other institutions for their logos as Paul wants as many as possible in that bottom area. Got SAMs already
![sam_gov_hz_blk](https://cloud.githubusercontent.com/assets/10238220/11544800/f85cf47a-9997-11e5-900e-6272d96f438a.jpg)

**Comment by sbearcsiro** [comment]
@RhiannonStephens I've created a task for your comment at #200 so I can close this one.
