### ISSUE TITLE
Add additional institution logos from main page footer

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#200]
Decide whether this should be an admin option or hard coded.

From @RhiannonStephens:

I'm in the process of emailing the other institutions for their logos as Paul wants as many as possible in that bottom area. Got SAMs already

![image](https://cloud.githubusercontent.com/assets/1750790/11618981/308d063a-9cf6-11e5-84d0-be80397bad25.png)

**Comment by RhiannonStephens** [comment]
@sbearcsiro it might be easier to be an admin option? then I don't have to ask you every time a new institution starts with us

**Comment by RhiannonStephens** [comment]
@sbearcsiro this will depend on how long admin version will take to create

**Comment by RhiannonStephens** [comment]
@sbearcsiro i have a new logo for Museums Victoria 
![mv_symbol_hoz](https://cloud.githubusercontent.com/assets/10238220/21788857/36d9f57e-d725-11e6-99fe-d26ddb690f54.jpg)
