### ISSUE TITLE
Upload picklist timeout

### ISSUE THREAD

**Issue by johntann99** [AtlasOfLivingAustralia/volunteer-portal#206]
504 Gateway time-out error
I am trying to upload a new localities picklist, and get a time-out error. 

Process...
Bulk manage picklists: http://volunteer.ala.org.au/picklist/manage
Upload CSV file
   Picklist = verbatimLocality
   Collection Code = Australian Museum Malacology
The size of the file is 45,000 lines, about 2.5MB
After about 70 seconds I get time-out error.
Note I was able to upload a shorter file (10,000 lines, 260kb) without a problem.

I have attached the file for you.

Can you extend allowable time before error, please?
![upload_picklist](https://cloud.githubusercontent.com/assets/5357997/12377285/689ff906-bd6c-11e5-9df1-2141648b2ffd.jpg)
[Picklist AM localities.zip](https://github.com/AtlasOfLivingAustralia/volunteer-portal/files/93369/Picklist.AM.localities.zip)

**Comment by sbearcsiro** [comment]
Server timeout is now increased.

**Comment by johntann99** [comment]
Thanks,
It worked today,
John

On 27 January 2016 at 12:07, Simon Bear <notifications@github.com> wrote:

> Server timeout is now increased.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AtlasOfLivingAustralia/volunteer-portal/issues/206#issuecomment-175322444>
> .
>



-- 
John Tann
johntann99@gmail.com
