### ISSUE TITLE
Measure time taken to for transcriptions

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#211]
We need to measure the time taken for transcriptions that will work across multiple sessions and with multiple users(?).

Then create a report that show average time taken to transcribe a task and an option to partition that report on project type (eg specimens vs field notes).

**Comment by sbearcsiro** [comment]
@RhiannonStephens do you want this information surfaced anywhere else?

**Comment by RhiannonStephens** [comment]
@sbearcsiro The graph works and displays in the DigiVol stats page but the Download button doesn't work.
None of the download buttons worked for any of the stats tables or graphs

**Comment by RhiannonStephens** [comment]
Download buttons now work but csv is blank for all stats. Average transcription time graph is not populating

**Comment by sbearcsiro** [comment]
CSV downloads should be fixed now
