### ISSUE TITLE
Add facility for recording the geo location of transcribers

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#212]
Ideas - save transcribers IP address on the task then do a bulk IP to location lookup using a service such as https://freegeoip.net/ as close as possible to the transcription time (maybe even do it at transcription save).

Alternatively, record user's ALA account's City and State.

Create a report that shows city and country of users.

**Comment by RhiannonStephens** [comment]
This can be done in Google analytics
