### ISSUE TITLE
Sharing images

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#213]
images shareable to Facebook, twitter and instagram through buttons in the task

**Comment by RhiannonStephens** [comment]
didnt work
![image.png](https://images.zenhubusercontent.com/56492635638e718c995e8bcd/b181eb92-76a3-4516-907d-fe07ba4df2d2)
When i clicked on the link i got
![image.png](https://images.zenhubusercontent.com/56492635638e718c995e8bcd/ba20e272-433a-4f82-a71a-f8f523a0a176)

**Comment by sbearcsiro** [comment]
Add a project level flag to enable disable sharing images.

**Comment by RhiannonStephens** [comment]
Need to add the project level flag to enable disable sharing images
