### ISSUE TITLE
https green padlock

### ISSUE THREAD

**Issue by matthewandrews** [AtlasOfLivingAustralia/volunteer-portal#219]
DigiVol is available via https, but with browser warnings, due to some content being served over http.

To attain the fabled green padlock, some resource URLs need to be changed to https (expedition images, thumbnails, some CSS, some gravatar....).

**Comment by sbearcsiro** [comment]
thanks @matthewandrews - the SSL setup is there for connections to some admin applications but I agree it would be good to fix the app to be protocol agnostic (and then also to enable HSTS in the nginx config)

**Comment by matthewandrews** [comment]
s/SSL/https\/TLS/g

**Comment by sbearcsiro** [comment]
Front page has a padlock now.
