### ISSUE TITLE
Automatic email to new volunteers

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#225]
Set up an automatic email response when a volunteer completes 1 transcription that welcomes them to DigiVol

**Comment by sbearcsiro** [comment]
@RhiannonStephens do we have a template for the subject / body of this email?

**Comment by RhiannonStephens** [comment]
[Automatic email to new user.docx](https://github.com/AtlasOfLivingAustralia/volunteer-portal/files/3844046/Automatic.email.to.new.user.docx)
