### ISSUE TITLE
Email notification of new transcriber tasks

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#226]
Send an email to DigiVol@austmus.gov.au when a new transcriber has completed 5 transcriptions. The email to contain links to the 5 transcriptions so that they can be accessed quickly and feedback given straight away.

**Comment by sbearcsiro** [comment]
Previous commits that relate to this task:
cff01c8a
605a966e
1abc83cf

**Comment by RhiannonStephens** [comment]
I can't test this because of problems with new users and not being able to complete a task (comments in #262)

**Comment by RhiannonStephens** [comment]
This didn't work.  New volunteer Rebekah Dowsett transcribed 10 tasks yesterday and I didn't receive an email notification

**Comment by RhiannonStephens** [comment]
@sbearcsiro The new user email link doesn't work 
![image](https://user-images.githubusercontent.com/10238220/34127860-c4a1c94c-e492-11e7-9ebf-80867b0ea04c.png)
Also the new user emails that we used to have are now missing a name 
![image](https://user-images.githubusercontent.com/10238220/34127902-e363c010-e492-11e7-9506-6bc82b84ef6c.png)
