### ISSUE TITLE
Wingtags Template

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#229]
Question 10 of this template is not showing up in the summary (step 11) at the end
![image](https://cloud.githubusercontent.com/assets/10238220/15521372/c5e177c4-224e-11e6-8421-c9a5a1bfca33.png)

![image](https://cloud.githubusercontent.com/assets/10238220/15521389/d73945d8-224e-11e6-9164-369b089b3701.png)

**Comment by sbearcsiro** [comment]
Check that transcriber notes appear for the validator

**Comment by sbearcsiro** [comment]
Not an issue
