### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#230]
Just exported the user report 

It has 3402 users on it.
Of these 1601 have transcribed or validated at least 1 task

![image](https://cloud.githubusercontent.com/assets/10238220/15695427/5b0064dc-27ea-11e6-90ae-202a09bb9592.png)
The front page says 1590 volunteers

![image](https://cloud.githubusercontent.com/assets/10238220/15695432/6f0bbbb6-27ea-11e6-9e16-4776775ec081.png)
The stats page says 3402 volunteers with 89 new volunteers
According to the user report, this month (May) 45 new volunteers (ie transcribed 1 task) joined. I have no idea where the 89 comes from??

If we are only going to report on those that have done a task then can we get these two aligned as it makes it really hard for me to report on

BTW 1601 or 1590 – why is there a difference? I know its small but still curious

**Comment by RhiannonStephens** [comment]
@sbearcsiro did I ever get an answer to this? It makes it so hard to report, I am still using the user report to get this info

**Comment by RhiannonStephens** [comment]
Could we have a break down of how many tasks each institution does each month?

**Comment by RhiannonStephens** [comment]
The download buttons are not working on the stats page

**Comment by sbearcsiro** [comment]
@RhiannonStephens The New Volunteers and Total Volunteers does not currently take into account whether the user has completed a transcription or not.  I can add the filter for at least one transcription if you wish.

The discrepancy between the front page and the user report transcriber numbers is that the front page is using pre-calculated data that is out of sync with reality, the user report in this case is the source of truth.

**Comment by RhiannonStephens** [comment]
@sbearcsiro yes please i would like only users that have complete at least one transcription. Thanks

**Comment by RhiannonStephens** [comment]
@sbearcsiro Yay! This is the best!! You just made my life so much easier! Except the download buttons are not working :(

**Comment by RhiannonStephens** [comment]
Download buttons work for the Reports by Institution section but don't work for Reports By Date. Month does not appear on the top row of the csv for the Transcriptions By Institution by month
