### ISSUE TITLE
Update notebook notifications

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#232]
- Only show number changed
 - Don't use global variable
 - Add a switch to show only validator notes and not changed fields to notifications tab, persist to user settings.

**Comment by sbearcsiro** [comment]
@RhiannonStephens I haven't added a switch to change between all changes and validator notes only... but I think it works sufficiently well now that we don't need it?

**Comment by RhiannonStephens** [comment]
@sbearcsiro yeah cool, if you think it will work better then don't worry about the switch. Can we see how it goes. I have had a lot of volunteers ask to turn the feature off. Let me see what feedback I get.
