### ISSUE TITLE
Expedition volunteers list on the front page of the expedition

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#240]
On an expedition's front page, if you click on a transcriber in the expedition volunteers list, it takes you to the transcriber’s total transcriptions across all expeditions and also does not allow validation.  Previously the list would be of the transcriptions in that expedition only and with the ability to validate.

**Comment by RhiannonStephens** [comment]
@sbearcsiro i think this would be a Quick fix?? We used to be able to do this before. I have to admit I actually use this a lot and it has been a pain without it!

**Comment by sbearcsiro** [comment]
@RhiannonStephens the functionality should be there, let me know if you want further visual changes to distinguish that it's for a single project?
