### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#246]
Julia Hazel has ticked the 'receive email notification' box and is not receiving emails anymore.

The university's IT staff did a comprehensive check and found none of the missing email alerts. They asked if your IT people could run a message trace on these emails and send the results - sent email to Simon

**Comment by sbearcsiro** [comment]
TODO Make from address configurable.

**Comment by sbearcsiro** [comment]
@RhiannonStephens Is this still an issue?

**Comment by RhiannonStephens** [comment]
See #284
