### ISSUE TITLE
Image upload improvements

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#256]
- [ ] Make image upload more robust
- [ ] Make upload handle directory hierarchies
- [ ] Show progress bars and upload queues

**Comment by nickdos** [comment]
I've been playing with the [AARNET Cloudstor](https://cloudstor.aarnet.edu.au) service and it might be a viable option. AARNET users get 100GB free and can also be members of groups that can additional storage quotas. The desktop client will sync a folder of images on a desktop, much the same way as Dropbox does. You can then generate a public URL for an entire folder which then gives access to all the images in that folder, e.g. https://cloudstor.aarnet.edu.au/plus/s/vCbk59uDX6ZpeA7. 

There is also a "[Collections](https://cloudstor.aarnet.edu.au/plus/apps/collections/user_guide)" function where files and folders can be added to a collection. You can then "package" and "export" all files for a collection and it will add metadata such as collection information, creators, primary contact, access rights, etc. Might be overkill as metadata required fields are onerous.
