### ISSUE TITLE
Visualising sound

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#259]
Develop a way to visualise a sound and match it to another recorded sound. For example trying to match a recording on a phone with a known recorded species of frog sound. To try and work out which species has been recorded on the phone. Zooniverse Bat Detective does this.
![image](https://cloud.githubusercontent.com/assets/10238220/21162003/43731eec-c1df-11e6-8262-ef0c630e6f97.png)

**Comment by cdausmus** [comment]
Resolved in 6.1.2.
