### ISSUE TITLE
Link from BVP to expeditions pages in the ALA

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/volunteer-portal#26]
_migrated from:_ https://code.google.com/p/ala/issues/detail?id=212
_date:_ Thu Aug  8 21:44:59 2013
_author:_ moyesyside

---

Original Issue reported by Project Member Reported by snom...@gmail.com, Nov 7, 2012 - [https://code.google.com/p/ala-volunteer/issues/detail?id=58](https://code.google.com/p/ala-volunteer/issues/detail?id=58)

Project Member Reported by snomelf@gmail.com, Nov 7, 2012 
See attached file for nature and location of links
1. Front page - Link menu at top
2. Front page - link in Stats area
3. Expedition List Page - next to expedition name
4. Expedition front page - in left nav
5. On Volunteer page 

 StatsandALAlinks.pptx 991 KB   Download Nov 7, 2012 Project Member `#1` snomelf@gmail.com 
(No comment was entered for this change.)
 Cc: moyesyside@gmail.com

**Comment by davidbairdala** [comment]
Is this still something of interest @snomelf ?

**Comment by snomelf** [comment]
Yes please 

Paul

**Comment by cdausmus** [comment]
Closing after team meeting, related to Harvest work.
cc @AdamWoodsAM
