### ISSUE TITLE
Upgrade Grails to v3

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#262]
Grails 2.5 seems to be on the way out, we should update to Grails 3.x soon.

Things to consider for the upgrade:
- Need to move from resources plugin to asset pipeline (partially done, see asset-pipeline branch)
- can we switch to Spring Security CAS instead of the ALA CAS filter library?

**Comment by RhiannonStephens** [comment]
@sbearcsiro Description text missing from the front page of NestCam 06. I haven't had any problems when creating new expeditions but I went into the NestCam 06 project and the description wont show for me either.

**Comment by RhiannonStephens** [comment]
@sbearcsiro we had a weird thing happen on Friday where a volunteer logged on to one computer in the lab and couldn't get his notebook and then logged on to another and could. Out of 4 computers he tried he could access his notebook from only 2??

**Comment by sbearcsiro** [comment]
@RhiannonStephens NestCam 06 doesn't seem to exist in the dev system - is this a prod issue?  Prod is still running on the old code.

The volunteer that couldn't access his notebook, was this in prod or dev?  If in prod was he missing the drop down from being logged in?  There is an issue when you log in you might get a url ending in ;jsessionid=LONG_STRING_OF_RUBBISH and when you do then page loads as if you're not logged in (and hence your notebook link won't appear).

**Comment by RhiannonStephens** [comment]
@sbearcsiro NestCam 06 is in prod. I didn't think you had upgraded prod yet but I don't know what's going on with that NestCam project.

I wasn't there on Friday so unfortunately couldn't check it out. Don't worry about it for now, I will see if we have probs this Friday.

I got some dev stuff which i am about to add here

**Comment by RhiannonStephens** [comment]
I got a new person to register and log in to dev and do some tasks so I could check email notification works. 
1. They cant get their notebook get error
2. They get an error when clicking the get started button of any expedition
error msg
![image](https://cloud.githubusercontent.com/assets/10238220/22723468/c410abfa-ee12-11e6-9b2c-0e7e373437e8.png)
3. Pop up in forum saying Message text must not be empty when it isnt
![image](https://cloud.githubusercontent.com/assets/10238220/22723489/ee8ac5e6-ee12-11e6-8558-d0cb0c15da88.png)

**Comment by RhiannonStephens** [comment]
Cannot log out of dev

**Comment by RhiannonStephens** [comment]
Just tried the above on my transcriber email (rhiannonstephens@gmail.com) and i didnt have a problem with getting started or my notebook but did get the below error when trying to reply to a forum message
![image](https://cloud.githubusercontent.com/assets/10238220/22723554/88475d16-ee13-11e6-9121-72d7a6da02b2.png)

**Comment by RhiannonStephens** [comment]
In dev as transcriber
search bar in Volunteer list not working
![image](https://cloud.githubusercontent.com/assets/10238220/22724025/85466ec8-ee17-11e6-8320-2a3a634205b1.png)
get error
![image](https://cloud.githubusercontent.com/assets/10238220/22724028/907f5f8e-ee17-11e6-99ed-26e8dcda332d.png)

**Comment by RhiannonStephens** [comment]
As transcriber:
When click on expedition volunteers
![image](https://cloud.githubusercontent.com/assets/10238220/22761385/8fea4218-eeae-11e6-9c03-8a60949953b2.png)
get this 
![image](https://cloud.githubusercontent.com/assets/10238220/22761393/98905006-eeae-11e6-8257-e56674f68fe4.png)

**Comment by RhiannonStephens** [comment]
This whole page is wrong, is it the font??
![image](https://cloud.githubusercontent.com/assets/10238220/22761483/07678940-eeaf-11e6-8270-6852f4384d29.png)
should look like 
![image](https://cloud.githubusercontent.com/assets/10238220/22761493/13ba1eb0-eeaf-11e6-881f-cf41893daab1.png)

**Comment by RhiannonStephens** [comment]
Same with front page of institution
looks like:
![image](https://cloud.githubusercontent.com/assets/10238220/22761540/4699b390-eeaf-11e6-9698-b6e49f2a867c.png)
should be:
![image](https://cloud.githubusercontent.com/assets/10238220/22761549/52cf8ce8-eeaf-11e6-97f7-117e20cac675.png)

**Comment by RhiannonStephens** [comment]
Expedition list
![image](https://cloud.githubusercontent.com/assets/10238220/22761638/be4ec0ce-eeaf-11e6-9f6d-05c7e40425d4.png)

**Comment by RhiannonStephens** [comment]
Can you please make expeditions under the institution sort as a list and not thumbnails

**Comment by RhiannonStephens** [comment]
As Admin now
All long description text boxes are gone
![image](https://cloud.githubusercontent.com/assets/10238220/22763587/fbc9507c-eeb9-11e6-859d-36cb3eeae8b8.png)

This means no description on front page of expedition exactly what NestCam is doing

**Comment by RhiannonStephens** [comment]
Tutorials will not upload - no pop up error, screen blank
![image](https://cloud.githubusercontent.com/assets/10238220/22763746/aa298c04-eeba-11e6-984a-c993d1c87933.png)

**Comment by RhiannonStephens** [comment]
Can't create expeditions. Probably because Long description is missing and that is one of the compulsory fields to fill out before you are allowed to click next.

![image](https://cloud.githubusercontent.com/assets/10238220/22763800/028ee6aa-eebb-11e6-8f07-f4a21d75bfaf.png)

**Comment by RhiannonStephens** [comment]
Templates
When you clone a template it loses all fields
Preview button doesn't work
![image](https://cloud.githubusercontent.com/assets/10238220/22763842/4e492b00-eebb-11e6-9ad1-5b4b732db483.png)
Cant import a template

**Comment by RhiannonStephens** [comment]
Cannot access My Notebook 
![image](https://cloud.githubusercontent.com/assets/10238220/22764025/3b39f0e8-eebc-11e6-896b-a39cb430eb01.png)

**Comment by RhiannonStephens** [comment]
Cant configure front page
Tried to change Project of the day and it keeps reverting back to previous project even after clicking save

**Comment by RhiannonStephens** [comment]
In Honour Board Configuration, can't add a user

**Comment by RhiannonStephens** [comment]
Stats - download files are empty

**Comment by RhiannonStephens** [comment]
Manage Institutions
Cannot edit existing pages. can create new ones and delete just cant edit

**Comment by RhiannonStephens** [comment]
Can't change images in the expedition settings results in a blank page.

**Comment by RhiannonStephens** [comment]
Tutorial links in expedition settings is blank
![image](https://cloud.githubusercontent.com/assets/10238220/22765803/4cdcf778-eec6-11e6-998b-3874847444f0.png)

**Comment by RhiannonStephens** [comment]
1.
The image below was done when using Internet Explorer (v 11.0.38).  I was using this (actually working across 2 browsers) as Chrome appeared not to be allowing upload of tutorial files.
Please note the absence of quite a number of the buttons.  They are actually there and appear to work.
![image](https://cloud.githubusercontent.com/assets/10238220/22996051/71f371bc-f421-11e6-9d08-857445041b3f.png)

 
2.
Similarly when trying to load tasks (still working across 2 browsers)  (still in IE)
 
![image](https://cloud.githubusercontent.com/assets/10238220/22996055/7c395f74-f421-11e6-84a9-fe599f612034.png)

**Comment by RhiannonStephens** [comment]
@sbearcsiro I tried to create a Beetles expedition and it said Boo something happened yet the expedition was still there in the expedition list. When I tried to load images to the staging area it just got stuck loading

**Comment by RhiannonStephens** [comment]
I just managed to stage 62 images and am trying to create tasks
![image.png](https://images.zenhubusercontent.com/56492635638e718c995e8bcd/9cc15394-cd5a-45eb-b438-7194a66a3e7d)

**Comment by sbearcsiro** [comment]
@RhiannonStephens was the total size of the files approximately 84mb?  Or was there a single file around 84mb?

**Comment by RhiannonStephens** [comment]
No, don't think so. I loaded about 62 images each somewhere between 400-700KB

**Comment by RhiannonStephens** [comment]
When you clone a template the fields do not come across. All fields are removed
![image.png](https://images.zenhubusercontent.com/56492635638e718c995e8bcd/c7683f13-27e9-4b1d-b5a6-d36d979dee19)

**Comment by RhiannonStephens** [comment]
Admin Tools - Front page configuration
Find an expedition button finds the expedition but when you try to select the expedition you want it doesn't do anything. It does not change the feature expedition.

Everything else works

**Comment by RhiannonStephens** [comment]
Edit button in manage institutions is not working

**Comment by sbearcsiro** [comment]
The following should be fixed:
 - Clone template fields
 - Edit button in manage institutions not working
 - Find expedition button not selecting

**Comment by RhiannonStephens** [comment]
Tested the above:

Clone template fields is fixed
Edit button in institutions is fixed however long description field in settings is missing
Find expedition button is fixed

**Comment by RhiannonStephens** [comment]
When in the expedition forum the task topics are not showing up, stuck on searching
![image](https://user-images.githubusercontent.com/10238220/33690101-17f07fd2-db36-11e7-94a4-119d095c6f1e.png)
