### ISSUE TITLE
Transcription not saving

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#263]
Email from Marie Davidson:
I was 2/3 way through this page of transcription and the Register worksheet vanished into cyberspace, unrecoverable.
It seems a shame to waste this amount of work.
There was no ‘time out’ and no accidental hitting of Delete or anything else untoward, apart from a section of magnification undertaken. The page vanished when I started to return the script to normal size.
If there is any way that it reappears 2/3 done in your files, I would be happy to finish it, if it could be e.g. returned to Transcribed or Saved, for me.
Otherwise, what has been done, see copy above, might be useful for somebody else to complete, if the accompanying appropriate Register page can be located, which I presume in the final wash up, it will be. 

Last night, for interest’s sake, but along the same lines, an unfinished sheet begun by Victoria Burgess opened up as the next Get Started task for me. I needed to leave the very small amount I had begun on that, definitely hit Save, and returned to find it entirely unrecoverable.

I also think that if any transcriber cannot complete a task that subsequently shows up in another Transcriber’s Get Started tasks, then it would be a courtesy to have their name deleted from the incomplete work before it is returned to the general task pool. 

It is a significant problem in this Expedition, this vanishing page effect.

**Comment by sbearcsiro** [comment]
Which expedition?

**Comment by RhiannonStephens** [comment]
Was GA Slide based collections - Rock Register #2 - which is now finished

**Comment by RhiannonStephens** [comment]
I will see if i can reproduce
