### ISSUE TITLE
New Project Wizard should provide meaningful error messages in the case of a validation error

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#264]
![image](https://cloud.githubusercontent.com/assets/10238220/22960946/38aa2c88-f396-11e6-99b8-387adbb82a40.png)

**Comment by sbearcsiro** [comment]
@RhiannonStephens The description was too long, there is a maximum size of 3000 chars at the moment (which includes all the HTML tags and the like.  Try pasting the unformatted text and formatting it using the text box controls, MS Word adds a bunch of extra HTML that is probably unnecessary.

**Comment by RhiannonStephens** [comment]
That's weird?? Didn't think it was that long and I thought I removed all html. I will try again.

**Comment by sbearcsiro** [comment]
Interesting - there is an issue here though, the wizard should have its validators set up and should handle a validation error from the server with a more meaningful message.

**Comment by cdausmus** [comment]
Closing in favour of new issue to rebuild the create project process.
/cc @AdamWoodsAM
