### ISSUE TITLE
Registry key for Unicode input

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#270]
I have a request from a volunteer:

"In order to enable a universal (independent of language settings) input method in Windows, one can add a string type (REG_SZ) value called EnableHexNumpad to the registry key HKEY_CURRENT_USER\Control Panel\Input Method and assign the value data 1 to it."

https://en.wikipedia.org/wiki/Unicode_input#In_Microsoft_Windows

For example, this would allow the entry of the reverse tilde equals symbol
⋍
(which Gray frequently uses for "approximately") by typing Alt+22cd, instead of laboriously finding it on Shapecatcher for example then copying and pasting.

**Comment by sbearcsiro** [comment]
This would need to be applied to the PCs running the web browser accessing digivol by an administrator.  I can't do this with a web application, sorry!

**Comment by RhiannonStephens** [comment]
Cool!
