### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#271]
@sbearcsiro when we did the refresh of the site Peter sent you some images for the new badges/achievements. I have had many volunteers enquire about badges and achievements especially now with minerals and camera traps. Am I able to add badges? if yes, can you send me the badges that Peter sent to you. If no, could you add the badges or fix it so I can. Thanks

**Comment by sbearcsiro** [comment]
So you want to add extra badges?  If so, you can if you can formulate the requirements as an elastic search query using the manage badges section of the Admin screen...  Otherwise, let me know what the requirements are and which image you'd like to use and I can work out the query for you.

**Comment by RhiannonStephens** [comment]
Ok. I'm going to give it a go :)
