### ISSUE TITLE
Misconfigured link on the about page

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/volunteer-portal#278]
There is a link on the about page:

To become a volunteer you must register on DigiVol before you can join an expedition. To do so you need to provide your email address and a few details --> here <-- that is pointing at:
https://auth.ala.org.au/cas/login?service=/
instead of the registration page.  This causes a CAS error when the link is followed.

**Comment by sbearcsiro** [comment]
Fixed in ec4019f4784d676fce4bdcf0ded2e2f4c1b442f6
