### ISSUE TITLE
Tutorials link to ///data/volunteer//tutorials

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/volunteer-portal#280]
The tutorial page links to ``///data/volunteer//tutorials``. These links manage to render, but it makes it more difficult to setup a useful ``robots.txt`` file to tell bots which paths under ``/data`` (and ``/``) they should and shouldn't index. The links on the tutorial page seem to work if changed to remove the redundant slashes. 

For example the following works,:

```
https://volunteer.ala.org.au///data/volunteer//tutorials/ANIC-2018-expeditions.pdf
```

but it also works without the redundant slashes:

```
https://volunteer.ala.org.au/data/volunteer/tutorials/ANIC-2018-expeditions.pdf
```

To relieve some of the pressure on the server from bot accesses, the robots.txt file now attempts to stop all access to ``/data``, ``//data`` (which is also observed), ``///data``, and ``////data`` (which isn't observed, but added to prevent other potential issues)

**Comment by RhiannonStephens** [comment]
@sbearcsiro I think this has been fixed, can I close??
