### ISSUE TITLE
Add Unfinished button to tasks when validating

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#281]
Could we please add an Unfinished button to the tasks when validating.
Some volunteers have inquired as to why their tasks are invalid when the validator has just marked it as this so they can check something. It would be better to have an unfinished button for this purpose. Also need invalid button for those tasks that need flagging as something wrong.

**Comment by RhiannonStephens** [comment]
That is change the word invalid to unfinished or something similar

**Comment by patkyn** [comment]
Does this mean we need 3 states for task? 
Validated, Invalid, Unfinished

**Comment by RhiannonStephens** [comment]
@patkyn I just had a discussion with Paul about this. Can we please leave this for now. I will move it from AM Priorities

**Comment by cdausmus** [comment]
This is fixed by #496
