### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#287]
User permissions
•	could site_admin please be removed from the list. Recently an admin person had given a volunteer this permission thinking that it was for only the project listed but the volunteer had full admin access to the site.
•	When you add a new permission it automatically comes up with validator all projects. 
Can this be changed so that someone cannot accidently give a volunteer all projects access.
•	Could it be possible to give a volunteer access to all the projects under the one institution at the one time. For example, Megan Edey validator for all Australian Museum Entomology expeditions.

**Comment by patkyn** [comment]
site_admin role still remain in DB. Only not visible in drop down list
Project and Institution assignment can now be to forum_moderator and validator role
