### ISSUE TITLE
Field note badges 

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#289]
I have had a complaint that the Master Scribe ‘Pen’ badge doesn’t work. This is the badge that you get for doing 100 tasks from 3 different diary expeditions. This is because the field note badges work differently to the other badges. Maybe it needs to be changed so the expedition can use the tag field note?

**Comment by sbearcsiro** [comment]
There was an issue with this badge - it should now be correctly ensuring that the transcriber has fully transcribed 100 tasks from 3 different field note badges (ie at least 300 total).
