### ISSUE TITLE
Not seeing Map

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#290]
Volunteer Lawrence Littlehale sent: 
I'm not able to get the locator map to display in Expedition Muscidae III.
I have been using IE on Windows 7 Pro. Turning off Active X Filters has worked well in the past.
Today, even though I turned off the Filters, added ala.org to Trusted Zone and allowed all cookies for the site, I'm still not seeing the map and pointer, although I do get the form window with the search form.

**Comment by sbearcsiro** [comment]
At this point we can't really support IE on Windows 7, probably best to use an evergreen browser like Firefox or Chrome.
