### ISSUE TITLE
Validate task page details/Export transcription

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/volunteer-portal#303]
Validate task page needs to be modified to extract out information from transcription table because schema change https://github.com/AtlasOfLivingAustralia/volunteer-portal/issues/296:

1)  Export all/Export Transcribed/Export Validated
2) 'Fully transcribed by' display
3) Action -> Validate/Transcribe saving
4) Search?

![image](https://user-images.githubusercontent.com/1606595/47328290-54d15200-d6bc-11e8-8fa2-1d40efcd971c.png)

**Comment by chrisala** [comment]
This is working for the 1 transcription per task use case.
Improvements for the > 1 will be included in a different issue.
