### ISSUE TITLE
Support additional template items for the camera trap template

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/volunteer-portal#311]
We need an item for: 
1) Number of required transcriptions of each task in the project
2) The threshold of matching transcriptions which will cause the system to auto-validate the Task.

Due to the fact the validation view of every template type will potentially need to be modified to allow the validator to see the transcribed values, this will need to be limited to the camera trap template at least to start with.

**Comment by patkyn** [comment]
Added SupportMultipleTranscriptions flag in Template. When this flag is set, users must set the values for transcriptionsPerTask and thresholdMatchingTranscriptions in Project Settings. A ui validation is added to make sure that thresholdMatchingTranscriptions is more than zero and equal to and less than transcriptionsPerTask
