### ISSUE TITLE
Add tutorial links and picklist settings to create project wizard

### ISSUE THREAD

**Issue by davidbairdala** [AtlasOfLivingAustralia/volunteer-portal#32]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=752
*date:* Wed Jul  9 23:14:09 2014
*author:* david.ba...@gmail.com
 ---

There probably should be steps in the create new expedition wizard for tutorial links and selecting a Collection picklist code.

**Comment by RhiannonStephens** [comment]
@sbearcsiro just need tutorial links to be added now

**Comment by RhiannonStephens** [comment]
@sbearcsiro is this a quick fix cause this issue is nearly complete??

**Comment by sbearcsiro** [comment]
@RhiannonStephens all rich text fields were upgraded as part of this change, so we may want to smoke test them all to make sure they're still working.
