### ISSUE TITLE
Privacy issues with visible user email addresses

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#337]
Validators have access to user email addresses which is a privacy issue and these need to be removed. 
Access is by going to the task details from the Admin table using the icon in the ID column.
![image](https://user-images.githubusercontent.com/10238220/58921118-a96f9c00-8778-11e9-9506-20c9d0cd106e.png)
User names need to be available but currently it has email addresses.
These email addresses need to be hidden and only the user name displayed.

**Comment by chrisala** [comment]
All instances of emails have been replaced with display names.
