### ISSUE TITLE
Validator review comments not visible

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/volunteer-portal#338]
Task that validated doesn't show  when review.

For eg: Australian Museum Kelp Flies 3 Expedition – if you go to the admin list and click on a review task button, it will take you to a blank task also the Catalogue Number and the Scientific Name on the validation list are disappearing after being validated.

**Comment by sbearcsiro** [comment]
@patkyn check if this is done

**Comment by patkyn** [comment]
This is done.
