### ISSUE TITLE
Prevent the dev and tests sites from being crawled by search engines

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/volunteer-portal#355]
We need to add robots.txt or similar to prevent search engines from indexing our dev and test sites as it can result in user confusion.

**Comment by RhiannonStephens** [comment]
Googled DigiVol today and the test site came up 3rd result

**Comment by RhiannonStephens** [comment]
Also when you search Wildlife Spotter, the DigiVol Wildlife Spotter page should come up. At the moment a link to an ALA blog comes up.

**Comment by cdausmus** [comment]
@RhiannonStephens Something has been done here, test and dev  no longer appear in the google search for 'digivol' and searching 'Wildlife Spotter' returns the digivol site (https://volunteer.ala.org.au/wildlife-spotter) first result.

Close?

**Comment by RhiannonStephens** [comment]
@cdausmus you're right, I just tried searching DigiVol and test did not come up. Yeah I reckon close. If you search DigiVol test it brings back the test site but I think that's okay, isn't it?

**Comment by cdausmus** [comment]
> If you search DigiVol test it brings back the test site but I think that's okay, isn't it?

@RhiannonStephens I think so.
