### ISSUE TITLE
Cache plugin is not working properly

### ISSUE THREAD

**Issue by patkyn** [AtlasOfLivingAustralia/volunteer-portal#358]
Currently, latest contribution volunteer stats is being calculated and cached. The cache should be refreshed every 10 minutes. 

The latest eh cache plugin cache-ehcache:3.0.0.M1 is not working with the current version of grails 3.2.11. 
TimetoLive seconds config is not working with this version of ehcache with grails 3.2.11.
When starting up grails, there is also an error message shown:

2019-10-14 14:15:02.609 ERROR --- [           main] g.plugins.DefaultGrailsPluginManager     : ERROR: Plugin [cacheEhcache] cannot be loaded because its dependencies [[‘cache’]] cannot be resolved

As a result of this, the latest contribution stats is not being triggered to recaculate and not showing latest stats.

**Comment by patkyn** [comment]
Only config changes. 
No code change needed.

**Comment by cdausmus** [comment]
Reopening this issue due to 2.0.0.BUILD-SNAPSHOT being removed from the repository. I've tried 3.0 release and it still shows the error in the start up log.

@sbearcsiro I noticed there's a 2.0.ALA on nexus, is that a clone of 2.0?

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
