### ISSUE TITLE
Exporting Wildlife spotter template from test to production

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#363]
Institutions create and test their Wildlife spotter templates in the test site but when they go to export the template to production not all the images will come across and then images need to be reloaded to production.

**Comment by cdausmus** [comment]
After discussing at team meeting, workarounds currently in place, with potential to look into new process for staging projects after project/institution permissions review.
/cc @AdamWoodsAM
