### ISSUE TITLE
Auto-validation failing with multiple species of animal

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#367]
Images with more than one species hasn’t been auto-validating. It seems to be when people select things in different order (for instance in this example malleefowl first or goanna first), irrespective of whether or not the ID is the same for both species https://volunteer.ala.org.au/task/showDetails/51836951

**Comment by patkyn** [comment]
https://upsource.ala.org.au/volunteer-portal/revision/8bd550c52c4061b2939d9a9bde3f2b523ba39049
