### ISSUE TITLE
Achievement badges and contributions are not working

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#368]
The badges are not working anymore. Possibly from the last update? and the contributions pie chart no longer shows (although I thought is was working the other day??)
![image.png](https://images.zenhubusercontent.com/56492635638e718c995e8bcd/bf3798a9-ce48-45e0-b624-dfffd9bd9635)

**Comment by patkyn** [comment]
After the search query was run, going to Admin -> Manage Achievements -> select Entomologist award 
 -> go to Awards tab and click on Award All Eligible to award those who missed out. 

The above volunteer MM Debeer is said to be awarded but the award is not listed in the table and persisted in DB immediately. A fix for this is also included as part of this issue.

**Comment by RhiannonStephens** [comment]
Lists are still not showing. Seems to be only when I am logged on as a transcriber.
![image](https://user-images.githubusercontent.com/10238220/71211769-ed388600-2303-11ea-98b9-ee15f1b18fe1.png)
