### ISSUE TITLE
Notifications of expeditions

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#371]
Email notification when an expedition is activated and appears on the home page.
Email notification when an expedition is complete and leaves the home page.

**Comment by sbearcsiro** [comment]
@RhiannonStephens who gets these emails?

**Comment by RhiannonStephens** [comment]
@sbearcsiro DigiVol@austmus.gov.au email address

**Comment by sbearcsiro** [comment]
PR: LGTM
