### ISSUE TITLE
Bug in Taronga Template

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#374]
If you select 'Unknown Mammal' from the picklist it is changing it to 'Feral animal' but only in the view option. It is not exporting as 'Feral animal'
See task https://volunteer.ala.org.au/task/showDetails/44275747
Task details show that Jason Ho has chosen 'Unknown Mammal' 
![image.png](https://images.zenhubusercontent.com/56492635638e718c995e8bcd/b3b0d316-1d19-4138-9c0b-d0d0f389d27e)
Task view showing 'Feral animal'
![image.png](https://images.zenhubusercontent.com/56492635638e718c995e8bcd/0547b489-9f9a-4e4e-b1d2-74d0a002cccf)

**Comment by cdausmus** [comment]
Cannot reproduce. Will need to keep an eye out for this re-occurring.
