### ISSUE TITLE
Fix Bushfire Recovery Projects Stats panel

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#385]
The stats panel in the landing page needs to change to the heading of the landing page.
Both in the heading of the stats page and the legend heading.
![image](https://user-images.githubusercontent.com/10238220/79400000-3e156e00-7fc8-11ea-8371-9194445befe0.png)

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/volunteer-portal/review/VP-CR-5
