### ISSUE TITLE
Delete Tutorial

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#386]
The tutorial T:\Lincoln\Projects F-J\HERBDOCS\Herbarium\Databases\Volunteer Portal\Allan Herbarium (CHR) Tutorials - Grasses and Sedges cannot be deleted.
It comes up with the following error
![image](https://user-images.githubusercontent.com/10238220/80662603-04b72500-8ad5-11ea-9fd7-299a25ed1edd.png)

**Comment by cdausmus** [comment]
Tested and could not reproduce.
