### ISSUE TITLE
Mailing list for institutions as a whole

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#389]
A mailing list for each expedition is available but it would also be good to have a mailing list for the all users within the whole of the institution.

**Comment by cdausmus** [comment]
Placing on hold for now, discussion to be had surrounding permissions (i.e. should Institution admins have access to this info, volunteers have not opted in for having their email accessible).

**Comment by cdausmus** [comment]
Bench for now due to privacy issues.

**Comment by cdausmus** [comment]
Closing this. Replaced by #463
