### ISSUE TITLE
Cannot delete expeditions

### ISSUE THREAD

**Issue by AdamWoodsAM** [AtlasOfLivingAustralia/volunteer-portal#394]
Error message when we try to delete any expedition.
Rhiannon mentioned this was an issue in the past, but had been fixed, looks to have returned.

**Comment by cdausmus** [comment]
@AdamWoodsAM I cannot reproduce this locally, are we able to verify it's still occurring in production?

**Comment by cdausmus** [comment]
Can no longer reproduce.
