### ISSUE TITLE
Transcribers getting timed out of tasks

### ISSUE THREAD

**Issue by AdamWoodsAM** [AtlasOfLivingAustralia/volunteer-portal#397]
Some people are getting timed out by the system while transcribing, it appears they lose their work but the system appears to save it and return the image to the pool for transcription.
Could there be a pop up or something that warns them after some time? that they can say they are still working on it?

**Comment by cdausmus** [comment]
Related to #399, if this is for Field Notes, then the possibility of extending the timeout for trascribing the tasks.

**Comment by cdausmus** [comment]
Shouldn't be an issue after #409 in 6.1.2.
