### ISSUE TITLE
Implement user friendly error pages

### ISSUE THREAD

**Issue by AdamWoodsAM** [AtlasOfLivingAustralia/volunteer-portal#398]
Users shouldnt get a whole bunch of code when an error occurs. Can we look at getting a more user friendly response built into the website?

**Comment by cdausmus** [comment]
Adam is referring to the stacktraces displayed when an error occurs and is displayed. This can be replaced by a more user-friendly error message (possibly with a reference key that is copied with the error in the log for aiding investigation).

**Comment by sbearcsiro** [comment]
PR: LGTM
