### ISSUE TITLE
Profile displays first person words

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#408]
On the profile display page, the information regarding contribution to research displays first person words which are misleading to users.

![image.png](https://images.zenhubusercontent.com/5f6aea684ede532400cfc803/ebc7aac4-1b6b-479f-b4fa-ddd4f8181818)

Change this wording to be less confusing

**Comment by sbearcsiro** [comment]
PR: LGTM
