### ISSUE TITLE
Aggregate active filter with tag filter on Expedition list

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#418]
When filtering the expedition list, aggregate the active/inactive filter with the tag filter search.

![image.png](https://images.zenhubusercontent.com/5f6aea684ede532400cfc803/4c69476c-a090-4873-b64c-2131c2b09ffe)

**Comment by cdausmus** [comment]
Tagged commit with #392.

**Comment by sbearcsiro** [comment]
PR: LGTM
