### ISSUE TITLE
Merge new project wizard into single form

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#424]
The new project/expedition wizard is only 3 steps long, after discussion at the team meeting it was decided to merge this wizard process into a single page for project creation. Additional changes are to remove background and project image upload and indicate to users this can be done from the settings screen, automatically redirect user to settings screen when creation has been successful.

Also allow Institution Admin access (as part of permissions review epic).

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
