### ISSUE TITLE
add a README

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/volunteer-portal#43]
Add a brief README for this project, which describes the architecture (grails app + postgres) and has some information pointing at the ansible scripts for installation.

**Comment by sbearcsiro** [comment]
@djtfmartin can you review please?  README.md is currently visible on develop branch.

**Comment by djtfmartin** [comment]
Thanks Simon.

This is probably more a comment on the ansible setup. I'd like to remove the need for a yml file and just stick with using the inventory for setting up username/password  deployments. This is how the other playbooks where done.

For local vagrant installs this root/password is just fine. For other system prod/dev/test these values should be in a private repo.

For the rest of the README, the following would be good:

1) graphic of the current schema
2) list of technologies in use
3) a simple architecture diagram for the deployment (nothing complicated)

**Comment by sbearcsiro** [comment]
bumping this to the next version.

**Comment by RhiannonStephens** [comment]
@sbearcsiro is this done? Can I close?
