### ISSUE TITLE
Create Institution application form

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#434]
Currently DigiVol admins manually create Institutions after some communication between @AdamWoodsAM and the institution.

Create an institution application form, similar to the new Institution Admin form that allows Institutions to input the required information and reduce workload from DigiVol Admins.

- [x] * Institution creates application
- [x] * DigiVol Admin approves/rejects application
- [x] * Upon approval, institution record created, applicant is made institution admin.
- [x] * Notify via email of lodgement/approval/rejection.
- [x] * Make name and email required
- [x] * Add to institution options (post approval) flag to hide name, email and phone.
- [x] Update pages that select institution lists to omit applications

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
