### ISSUE TITLE
Homepage 'Project of the Day'

### ISSUE THREAD

**Issue by AdamWoodsAM** [AtlasOfLivingAustralia/volunteer-portal#439]
This may need a total rethink all together, but in the mean time...

In Admin>Configure front page, there is an option to choose what is the project of the day. Can we restrict that drop down menu to only include 'active' projects rather than every project that has ever existed?

Thanks

**Comment by cdausmus** [comment]
Develop a randomisation algorithm selecting a random project each calendar day. 
Add a checkbox to frontpage settings to turn off randomisation.

**Comment by cdausmus** [comment]
Include with #11

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
