### ISSUE TITLE
Update stats web service to split validated and transcribed task count

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/volunteer-portal#44]
Compare

http://volunteer.ala.org.au/user/list?q=&sort=transcribedCount&max=10&order=desc

to 

http://volunteer.ala.org.au/ws/stats

e.g.

Megan Edey	4,638	18636	2 years ago

vs

"Megan Edey", 23274,

**Comment by sbearcsiro** [comment]
Unless there are any responses to Dave B's comment I'm just going to close this issue.

If the stats web service should be updated to:
 - include separate transcribed and validated figures
 - to remove the internal user id
 - include other stats like date joined and time of last activity

then please raise a separate issue.

**Comment by djtfmartin** [comment]
I think this web service as it is is pretty useless for the user counts. I suggest we split the counts as Dave describes.

"his stats web service could be updated to include separate transcribed and validated figures".

**Comment by sbearcsiro** [comment]
@djtfmartin the new stats format would be the following

note that each user is now a map instead of an array.  Is that OK or should it be left as an array for compatibility with any existing clients?

```json
[
  {"total":27443,"validated":22805,"transcribed":4638,"displayName":"Megan Edey","userId":"1142"},
  {"total":22180,"validated":9305,"transcribed":12875,"displayName":"Baz Walter","userId":"4710"},
  {"total":12152,"validated":0,"transcribed":12152,"displayName":"Teresa Van Der Heul","userId":"1058"},
  {"total":11690,"validated":8687,"transcribed":3003,"displayName":"Helen Bell","userId":"4213"},
  {"total":9555,"validated":2570,"transcribed":6985,"displayName":"Reiner Richter","userId":"1370"},
  {"total":9107,"validated":0,"transcribed":9107,"displayName":"Grahame Parsons","userId":"7484"},
  {"total":7496,"validated":1567,"transcribed":5929,"displayName":"Diana Gershwin","userId":"3458"},
  {"total":7118,"validated":1222,"transcribed":5896,"displayName":"Geoffrey Berry","userId":"4538"},
  {"total":6127,"validated":3641,"transcribed":2486,"displayName":"Jim Richardson","userId":"1186"},
  {"total":4868,"validated":1583,"transcribed":3285,"displayName":"Joy Pagon","userId":"1566"}
]
```

**Comment by sbearcsiro** [comment]
This is now available at http://volunteer-dev.ala.org.au/ws/stats

**Comment by djtfmartin** [comment]
sorry for not responding to the earlier question. I dont think anything is consuming this currently, so if you want to go with the map format (which looks better to me), go for it.

**Comment by sbearcsiro** [comment]
Apologies, this was not actually deployed to dev when I wrote the above message but it is now.

Re: adding it as a widget to the dashboard, would that get proxied through a server or would we need to add CORS/JSONP support as well?

**Comment by djtfmartin** [comment]
CORS support makes sense and is easy to add with this plugin

http://grails.org/plugin/cors

**Comment by djtfmartin** [comment]
looks good to me. closing
