### ISSUE TITLE
Expeditions - Cloning

### ISSUE THREAD

**Issue by AdamWoodsAM** [AtlasOfLivingAustralia/volunteer-portal#440]
It would be really great if there was an option to Clone an expedition in the same way you can templates.

**Comment by cdausmus** [comment]
Include with #11

**Comment by cdausmus** [comment]
This issue was expanded to include a new 'Manage Projects' UI for Admins.

This includes:
* Update Archive Expeditions to 'Manage Projects'
* Add cloning of projects
* Add filters to page to filter by status (archived/inactive/active)

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
