### ISSUE TITLE
System Validation - Wildlife Spotter

### ISSUE THREAD

**Issue by AdamWoodsAM** [AtlasOfLivingAustralia/volunteer-portal#441]
Currently the system validation requires all fields to match in order to have a consensus of matching transcriptions for system validation. This raises an issue where when a person adds a comment to the transcription it no longer matches with others with the same species and count. I think it would be advisable to remove the free text comment field from the matching requirement.

**Comment by cdausmus** [comment]
Include with #11

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/volunteer-portal/review/VP-CR-6

**Comment by cdausmus** [comment]
Hey Simon,

It’s asking for a log in, I signed in using Github auth but it’s giving me 403.

Chris

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
