### ISSUE TITLE
Last viewed info on Project Admin has wrong authz check

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#457]
When clicking on the padlock when a task is locked by a user, code has an admin authz check but Validators see this view too. Lower the authz level to validators.

**Comment by sbearcsiro** [comment]
LGTM

**Comment by sbearcsiro** [comment]
Testing
- Click on padlock with user who is a validator only
- [x] Does the last viewed info dialog appear?
