### ISSUE TITLE
Write a lat/long cell editor for the SpreadSheet template

### ISSUE THREAD

**Issue by davidbairdala** [AtlasOfLivingAustralia/volunteer-portal#46]
The spread sheet template uses SlickGrid, which allows custom cell editors to be bound to each column. Custom cell editors already exist for boolean values (check boxes), dates and long text. Add a custom cell editor that collects the individual components of a latitude/longitude, including text boxes for degrees, minutes, seconds and direction (N,S,E,W). The custom cell editor could use the name of the field being collected to work out if it should put N/S (latitude)  or E/W (longitude) in a dropdown.

**Comment by cdausmus** [comment]
After discussing at team meeting, decided to close after such a long period with no repeated requests.
/cc @AdamWoodsAM
