### ISSUE TITLE
Update ws/stats API call for ALA Dashboard

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/volunteer-portal#462]
current dashboard calls https://volunteer.ala.org.au/ws/stats.json (latest version deployed on Nov 2020),

but this change https://github.com/AtlasOfLivingAustralia/volunteer-portal/commit/bd668093719d85967f361fdd08aa1c7132c1c4c8 breaks the api

So now calling the api I saw a `Must be logged in as an administrator to use this service!`

**Comment by cdausmus** [comment]
@alexhuang091 We implemented authz on all administrative functions and information that accessed private and administrative information. Happy to update this for ALA Dashboard.

**Comment by cdausmus** [comment]
Excerpt from email from @sbearcsiro 

> DigiVol should only send the following fields: specimens, fieldNotes, volunteerCount, activeExpeditionsCount, completedExpeditionsCount and expeditionCount and remove the authz requirement that the user is an admin.
> 
> This means that digivol is sending cameratraps, topTenVolunteers and deactivatedExpeditionsCount which are not used by the dashboard.

* Will remove authz
* Will remove topTenVolunteers
* Will remove deactivatedExpeditionsCount

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
