### ISSUE TITLE
Rules around task locking.

### ISSUE THREAD

**Issue by AdamWoodsAM** [AtlasOfLivingAustralia/volunteer-portal#469]
It would be good to review when tasks are locked and for how long.
I think tasks are locked for time after submission, which probably isn't necessary. Especially in wildlife spotter.

Is there different rules for different templates? Or is it one size fits all?

**Comment by cdausmus** [comment]
@AdamWoodsAM We recently updated locking for when the task is skipped - 15 mins - for all other cases, it remains locked for 2 hours.

**Comment by AdamWoodsAM** [comment]
@cdausmus i think my questions are more around, if someone hits submit, what is the need for the task to be locked for 2 hours? Does locking prevent that volunteer returning to it or does the code check whether they have transcribed previously anyway?
This could all probably be refined more based on how DigiVol is now used.

**Comment by cdausmus** [comment]
@AdamWoodsAM The lock doesn't prevent the same user coming back to it (i.e. finish transcribing), however, it does lock everyone else out, including validators for the 2 hour lock period. 
Agreed that after a submit, the lock isn't required anymore.

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
