### ISSUE TITLE
Tutorial page breaks when a file has no file extension

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#474]
When viewing the tutorial page, the service method grouping the files returns a StringOutOfBoundsException if one file has no file extension. There have also been instances where files have been uploaded with Windows file paths somehow being in the file name (e.g. T:\upload\filename.pdf).

- Add code to reject path characters (e.g. :, \, / etc)
- Add code to add the pdf extension if it's missing on upload

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
