### ISSUE TITLE
System event message needs to remember it has been closed/dismissed

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#482]
The system event message is displayed at the top right corner of the screen and is displayed on each page load. Unfortunately, it covers controls such has buttons on the transcribe page. Users are complaining that this is annoying.

Add functionality to remember the current user has closed the pop up system message (maybe for a set time: 2, 6, 24 hours?).

Expected behaviour: System message should stay closed until the browser is closed and reopened.

**Comment by JennaMalkin** [comment]
This looks great! :)
