### ISSUE TITLE
Hotfix - Issues arising from 6.0.1 release

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#483]
Some small niggly issues slipped through the last release:
- Typo in Institution message template
- Footer DigiVol image displaying incorrectly
- Stats - By volunteer by project, rename to expedition
- Stats - Add seconds denomination to time by project type graph (rename to expedition type)

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
