### ISSUE TITLE
Archiving expedition results in losing institution

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#488]
When an institution admin archives an expeditition while no institution filter is selected, the expedition loses it's institution ID due to the institution filter being in the query string and the controller method passing the project object to the project service.

- Change the institution filter parameter to `institutionFilter`.
- Default the institution query string parameter to an institution ID so that it's never blank. To view all, the institution query string parameter must be missing.

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
