### ISSUE TITLE
Calculate project disk usage on task upload

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#500]
A key performance issue is the asynchronous calls to projectSize in manageProjects.

Modify this to calculate the dir size when tasks change (delete/upload) and store the value in the project table (in bytes). Update the manageProject page to display the static value stored in the DB instead of the ajax call to projectSize.

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
