### ISSUE TITLE
User transcription score goes backwards

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#504]
Transcription score seems to go backwards occasionally (user reports).

After investigating, the code in FieldSyncService simply adds one (transcribedCount++) to the score. It's possible that Hibernate/GORM is using a cached value when setting this back to the DB.

Update to use JOOQ instead to increment score.

**Comment by sbearcsiro** [comment]
Reviewed: LGTM
