### ISSUE TITLE
Add logic on task open to check if locked/completed

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#523]
Validation possible when task already opened by validator:
A task is able to be validated if a user opens a task that was opened since the page was displayed (and subsequent lock was in place'.

Validate task does not check if the task is locked (i.e. lock is done from the admin list where the link to the task is displayed).

Additionally, add similar logic to transcription/validation to check if it's completed. Stale pages are often left open (wildlifespotter) and users are getting confused when it's read-only and it's completed when they return.

Possible solution in #508. Admin list does not disable validation link even if locked (this is the reason for #508). Check if task is locked in task display (validate) or look further into disabling link.

Expected behaviour: A validator should see a padlock icon on a task when locked by another validator. Additionally, if a validator opens a task for validation that has already been opened by another validator, an error should be displayed stating that that task is currently locked.

**Comment by sbearcsiro** [comment]
Tested
