### ISSUE TITLE
'See similar expeditions' search button on completed expeditions doesn't show similar expeditions

### ISSUE THREAD

**Issue by JennaMalkin** [AtlasOfLivingAustralia/volunteer-portal#530]
When I'm on a completed expedition and I click the ‘see similar expeditions’ button such as [here on the test site]( https://digivol-test.ala.org.au/project/index/2130842) or [here on the live site](https://volunteer.ala.org.au/project/index/266669176) , the search doesn't show any other expeditions.  If I enter ‘specimen’ or ‘camera trap’ in the search box that appears on the page I get when my first click doesn’t work, I do get a list of those expeditions.

**Comment by JennaMalkin** [comment]
The expected behaviour is that the 'see similar expeditions' button should show a list of currently open, incomplete expeditions (i.e. not 100% transcribed) of the same broad type (specimen transcription, field notes transcription, camera trap, etc.) as the completed expedition.

**Comment by cdausmus** [comment]
Fixed with DG-66 #612
