### ISSUE TITLE
Project admin - sort by status is not intuitive

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#535]
Project admin task list has a status column which is sortable. The sort column is on isValid (true/false) but the value displayed is the logic-calculated new/transcribed/validated. This should be updated to make it sort on the value.

**Comment by sbearcsiro** [comment]
Tested on project id 1391216, looks good with one possibly minor issue:

Descending search has transcribed before in progress within the page but the set of tasks on each page seem correct.

**Comment by cdausmus** [comment]
> Descending search has transcribed before in progress within the page but the set of tasks on each page seem correct.

This is the expected behaviour, 'In Progress' can be partial validation OR partial transcription.

I've used the following case: 

```
CASE WHEN (task.is_valid = true) THEN 3 /* Validated */
   WHEN (task.is_valid = false) THEN 2 /* In Progress */
   WHEN (task.is_valid IS NULL AND task.is_fully_transcribed = true) THEN 1 /* Transcribed */
   ELSE 0 /* New */
END 
```

**Comment by sbearcsiro** [comment]
Sorry @cdausmus you're right, I can't reproduce my previous claim, must have been an error on my part.  Tested and looks good.
