### ISSUE TITLE
Forum doesn't display topics correctly

### ISSUE THREAD

**Issue by cdausmus** [AtlasOfLivingAustralia/volunteer-portal#537]
General topics are not displayed correctly, topics are doubled up. Sorting by replies is broken due to #464 Grails upgrade.

Expected behaviour: General topics should be displayed in the correct sort order with Sticky's first then in order of priority (not displayed) and then the selected column sort (default: last reply date). There should be no doubled up records.

**Comment by sbearcsiro** [comment]
Tested
