### ISSUE TITLE
People are transcribing What's that frog? Audio Analysis GS02 but transcription % is 0

### ISSUE THREAD

**Issue by JennaMalkin** [AtlasOfLivingAustralia/volunteer-portal#540]
Hi @cdausmus , I noticed people are transcribing https://volunteer.ala.org.au/project/index/261151432 but the % of transcriptions remains at 0, despite the expedition leader having currently transcribed 55/250 of the audio files, so the transcriptions should be at least at 22%.  Unsure if the % here https://volunteer.ala.org.au/institution/index/256511121 is changing.  

Please don't feel you have to spend your time explaining it all to me, but I would appreciate it if you could look into it when you can.

**Comment by JennaMalkin** [comment]
The percentage for GS02 has changed, but it's still not where maths suggests it should be: the expedition leader has transcribed 156/250 items so the % of transcriptions should be in the area of 62%, but it's only at 5% transcribed.

**Comment by cdausmus** [comment]
Hi Jenna, I've looked into this and it's displaying the correct number. The expedition leader has more transcriptions than reflected by the percentage because the percentage transcribed only counts tasks when they are 'fully transcribed'. This is when (in this expedition) it's had 5 transcriptions.

**Comment by JennaMalkin** [comment]
Thanks, I'm glad it's not a real bug, I was just worried because it wasn't moving and audio is a newer feature.  Thanks for double-checking this. :)
