### ISSUE TITLE
Feature Request: Allow volunteers to subscribe to a mailing list for an institution's new expeditions

### ISSUE THREAD

**Issue by JennaMalkin** [AtlasOfLivingAustralia/volunteer-portal#573]
This is something Adam mentioned briefly, unsure if it's on the radar or not.  

When a volunteer transcribes from an expedition, they should be given the option to subscribe to the institution's new expeditions.  An automatic email would be sent out to subscribers saying something like:
'Dear DigiVol volunteer (or their name if it's easy), Australian Museum Entomology Collection has launched the new expedition <name of new expedition and link goes here> if you're interested.'  This could help drive engagement for those volunteers who are fans of a particular institution.

The exact text would be automated and emails would be triggered on new expeditions going live on the site.  

Of course, an option to unsubscribe from these emails would also be useful.

**Comment by JennaMalkin** [comment]
and the email would name and link to the new expedition in question.

**Comment by cdausmus** [comment]
Thanks Jenna, we have an issue on our roadmap for exactly this feature!

**Comment by JennaMalkin** [comment]
Such a good idea, we thought of it twice. :)  Sorry for not seeing the other one.  Hope all is well with you, it looks like you're making some great strides with the software.
