### ISSUE TITLE
Forum users sometimes get two copies of the same notification email

### ISSUE THREAD

**Issue by davidbairdala** [AtlasOfLivingAustralia/volunteer-portal#58]
Not sure if it is just some users, but had a report from at least one user that they get two copies of each email

**Comment by sbearcsiro** [comment]
@RhiannonStephens I'm not sure if you know of any existing forums on dev that users will get duplicate emails for... if you can't test this one I think it should be ok to roll into production.  I was able to duplicate the problem on my local machine and it no longer happens here.
