### ISSUE TITLE
DigiVol Request

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/volunteer-portal#581]
Request from Chris.D

As you may recall, we’re utilising the ALA auth to provide a seamless path between using DigiVol and the Data Integration Tool that we’re currently developing.
 
Would we be able to get the OIDC set up done (to allow usage of the auth) for the development and test URLs:
 
devt.ala.org.au/datatool
integration-test.digivol.org
 
Let me know if you need more info.

**Comment by sbearcsiro** [comment]
These have been provided
