### ISSUE TITLE
Filtering the Project Admin List

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#59]
From Baz's email: When I'm validating a project, I can change the sort-order of the task list in various ways to bring the unvalidated tasks to the front. That usually works okay to begin with, but after a while it can become quite awkward to find the next task to validate if I've done a lot of transcriptions on the project myself. So I was wondering whether it would be feasible to provide a way to exclude the transcriptions of the logged in user from the task list?

**Comment by RhiannonStephens** [comment]
Refer #347
