### ISSUE TITLE
The help bubbles for verbatim text  and date in the single page field notes template cannot be seen properly

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#63]

**Comment by sbearcsiro** [comment]
@RhiannonStephens I noticed some extra instances of this problem that weren't fixed by the changes I put in for this specifically.  I believe it's the flight details template?  I'll add another issue for that problem so we can at least put these fixed ones into the release.

**Comment by RhiannonStephens** [comment]
@sbearcsiro It seems okay in dev? The problem template in production is the FieldNoteBook template. I will check it out in the release and see if it is still a problem and then we can make another issue if neccessary
