### ISSUE TITLE
Add validation status to the export file

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#65]
ie whether the task is valid or invalid

This one might be a bit urgent for John?

**Comment by RhiannonStephens** [comment]
Hey Simon, John actually wants the Validation Status to be whether the task has been marked as Valid or Invalid.
![image](https://cloud.githubusercontent.com/assets/10238220/5950522/62eaf23c-a7af-11e4-93d2-d74591e9f9f3.png)
In the export file it seems to show up true if the task has been validated even if it has been marked as invalid. Am I making sense?

**Comment by sbearcsiro** [comment]
@RhiannonStephens yep, definitely possible, David B and I discussed this before he left and neither of us picked up on that.  I'll get that added.  So the possible values will be "valid", "invalid" and empty?

**Comment by RhiannonStephens** [comment]
@sbearcsiro yep, valid, invalid and empty are good. Will you also call the column in the export file 'Validation Status' thank heaps
