### ISSUE TITLE
Exclude individual validators from the Honour Board

### ISSUE THREAD

**Issue by snomelf** [AtlasOfLivingAustralia/volunteer-portal#75]
The ability to exclude individual validators from appearing on the Honour Board would.

At the AM we have an employee who is working on validating records on DigiVol. Her advanced skills and knowledge mean that she is able to validate Very quickly - making it unfair to volunteers. It also looks inappropriate for an employee to be leading the Board. So we need a mechanism for removing individuals from appearing on the Honour Board - without having their contirbutions removed from the statistics.

Thanks
Paul

**Comment by RhiannonStephens** [comment]
The validator is Louise Carter
