### ISSUE TITLE
Front page images don't align properly in IE8

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#77]
Chrome:
![image](https://cloud.githubusercontent.com/assets/1750790/5952404/71218f76-a7ca-11e4-828b-0bf0b3275bee.png)

IE8:
![image](https://cloud.githubusercontent.com/assets/1750790/5952405/76a8eade-a7ca-11e4-8d86-18cb816378b2.png)

**Comment by aruizca** [comment]
Won't fix
