### ISSUE TITLE
A pinned image can not be unpinned in IE8

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#78]
The pin disappears in IE8.

Chrome:
![image](https://cloud.githubusercontent.com/assets/1750790/5952406/84814fac-a7ca-11e4-9891-f514b3f49d0a.png)

IE8:
![image](https://cloud.githubusercontent.com/assets/1750790/5952417/9269d8fa-a7ca-11e4-86ed-995b7d98ba4f.png)

**Comment by aruizca** [comment]
Won't fix
