### ISSUE TITLE
Replies and views count don't update on the forum page in IE8

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#80]
In Chrome:
![image](https://cloud.githubusercontent.com/assets/1750790/5952388/365d8336-a7ca-11e4-8939-c0f217b72518.png)

In IE8:

![image](https://cloud.githubusercontent.com/assets/1750790/5952391/4249c6a0-a7ca-11e4-9009-6838c74c6885.png)

**Comment by aruizca** [comment]
Won't fix
