### ISSUE TITLE
Some fields on some templates have help bubbles that go off the screen

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#81]
This is a follow on from #63 .  There are some templates, such as aerial observations that exhibit the same issue.  eg:

![image](https://cloud.githubusercontent.com/assets/1750790/5970498/43a5e20e-a888-11e4-8fc3-93953a0692c2.png)

To close this issue check all templates for help bubbles that disappear off screen.

**Comment by sbearcsiro** [comment]
Templates that were affected and should now be fixed: 
* Aerial Observations
* Journal
* Three Column Label

Some fields can also exhibit this problem if the screen is resized to a width around ~768px (aka horizontal ipad), however, the fixing this would then break regular monitor screen sizes which IMO is more important.

Affected templates:
* Generic Labels Transcribe: Copy Values from Previous Task 
* Single Section Transcribe, all fields

**Comment by RhiannonStephens** [comment]
@sbearcsiro looks good to me. The Aerial Observations date field help is still a little off but I am happy to live with that

**Comment by sbearcsiro** [comment]
@RhiannonStephens It doesn't look like there are any aerial observations projects in dev to me?  Can you send me a link to one with the date field help that still goes off screen?  I know you can live with that but now I'm curious :)

**Comment by RhiannonStephens** [comment]
@sbearcsiro no there isn't any aerial observation projects, I was looking at the templates. I guess you figured that out tho and changed them cause its not doing it this morning :)
