### ISSUE TITLE
Wrong forum names when posting a reply

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#87]
When you go to 'post reply' in a forum topic the volunteers name that posted is wrong. 
Example:
![image](https://cloud.githubusercontent.com/assets/10238220/6433890/bdd67918-c0ce-11e4-9946-a869a5891ab9.png)
Diana posted the original and Teresa posted the next entry.
When I clicked on the post reply it came up that Diana had written both
![image](https://cloud.githubusercontent.com/assets/10238220/6433899/eb650c78-c0ce-11e4-9353-e224c0b209c0.png)

**Comment by snomelf** [comment]
This might explain the discrepancies in Teresa's numbers

Paul
