### ISSUE TITLE
Achievment images

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#88]
![image](https://cloud.githubusercontent.com/assets/1750790/6457351/c6184282-c1c8-11e4-93bd-6dd2816b1022.png)

![image](https://cloud.githubusercontent.com/assets/1750790/6457364/09875a8a-c1c9-11e4-9ec3-bf97afc2fce3.png)

![image](https://cloud.githubusercontent.com/assets/1750790/6457405/6d18bd6e-c1c9-11e4-8eb7-fe8d7dccd3f4.png)

![image](https://cloud.githubusercontent.com/assets/1750790/6457414/82521cb6-c1c9-11e4-90fa-d394db94d08b.png)

![image](https://cloud.githubusercontent.com/assets/1750790/6457422/9d0a1c16-c1c9-11e4-9926-0697be51ee09.png)

**Comment by snomelf** [comment]
Not sure what this was about but we had some special images designed for the badges - these weren't them 

Paul
