### ISSUE TITLE
Not creating tasks from staged images

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#90]
Wont create the tasks from the staged images?

Comes up with ‘Load operation already in progress’ and then doesn’t seem to do anything??

![image](https://cloud.githubusercontent.com/assets/10238220/6567103/590a83c8-c716-11e4-9af0-d560da8225da.png)

It used to come up with a progress bar so you could see how long it’s taking.

**Comment by sbearcsiro** [comment]
This appears to be the same problem as #49.  Comments from there are:

Loading tasks from staging seemed to fail on 2014-9-30, which prevented any future loading from starting. Nothing in the logs indicated the cause of the problem. Suggest adding a way to recover the queue through the admin UI and extra logging around TaskLoadService#loadTasksFromStaging.

**Comment by sbearcsiro** [comment]
Investigation of stack trace suggests this is a bug in the NIO AJP connector in our deployed version of Tomcat, switching reverse proxy protocol to HTTP should resolve.

**Comment by sbearcsiro** [comment]
@RhiannonStephens there was a change to the configuration on the server that should (hopefully) prevent this from happening again... can you put a note here for the next few loads from staging to see if it happens again?
