### ISSUE TITLE
Investigate making image upload more robust

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/volunteer-portal#95]
* Leave in staging area regardless of whether using image service or not (staging area -> S3?)
* Break staging FS directory out into per project staging directory if required
* Upgrade upload page to support resumable uploads (resumable.js?)
* Convert staging upload to allow multiple projects to create tasks at once
* Check performance of uploading
* Convert staging upload page to show progress bar (ES notifications as well?)

**Comment by RhiannonStephens** [comment]
Problems creating tasks when others are also creating or uploading images. If there is a solution to have multiple people loading at the one time that would be good. Otherwise people just need to know (pop up message) that there are others loading and they might need to try back later or that they are going in a queue.

**Comment by sbearcsiro** [comment]
- Leave in staging area regardless of whether using image service or not (staging area -> S3?)
 - Upgrade upload page to support resumable uploads (resumable.js?)
 - Convert staging upload to allow multiple projects to create tasks at once
 - Check performance of uploading
 - Convert staging upload page to show progress bar (ES notifications as well?)

**Comment by RhiannonStephens** [comment]
@sbearcsiro can you navigate away from this page after you have clicked on the create tasks?? If so it might be a good idea to put that in the text
![image](https://user-images.githubusercontent.com/10238220/71213562-ef9cdf00-2307-11ea-8bd2-b3c29c57540f.png)

**Comment by RhiannonStephens** [comment]
@sbearcsiro when it has finished loading and creating the tasks can the button that says back to staging actually be back to the expedition settings? I think that makes better sense because you shouldn't need to stage more images.

**Comment by RhiannonStephens** [comment]
@sbearcsiro loading and everything went fine but when I went to transcribe as a transcriber I got the below error 
![image](https://user-images.githubusercontent.com/10238220/71214957-9a160180-230a-11ea-9f7a-c79dad71ee5e.png)
This is for expedition test dec 2019 https://digivol-dev.ala.org.au/project/index/57501239
