### ISSUE TITLE
User Report - tracking people from the same organisation

### ISSUE THREAD

**Issue by RhiannonStephens** [AtlasOfLivingAustralia/volunteer-portal#96]
When you register, there is a field for organisation. Could we get that field added to the user report? Background: Corporate company allows their employees a certain amount of time to do voluntary work. DigiVol is going to advertise for those people to volunteer with us. The company needs to be able to track those people. Paul suggested we get them to fill out the organisation field and get it added to the user report. Any other suggestions to track these people? They may not all have the same email.

**Comment by RhiannonStephens** [comment]
@sbearcsiro meeting with these guys friday morning so would like a process for them to follow. Sorry bout the late request!

**Comment by sbearcsiro** [comment]
@RhiannonStephens we can definitely to this - we'll just need to update the system that provides the user details to also provide this information.  What time frame would you need this feature in?

**Comment by RhiannonStephens** [comment]
@sbearcsiro i would really like to be able to post the ad tomorrow afternoon or early next week. Can it be done by then?

**Comment by sbearcsiro** [comment]
@RhiannonStephens early next week should be possible, the user details change and digivol change to make this happen should be doable today/tomorrow - it's just a matter of scheduling time to update the systems (user details in particular)

**Comment by RhiannonStephens** [comment]
@sbearcsiro thanks, just let me know when so I can post after that.
